# Getting the url

In [1]:
import requests
from ratelimit import limits

@limits(calls=10, period=60)
def get_json_response(url):

    requests.packages.urllib3.disable_warnings()
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += ':HIGH:!DH:!aNULL'

    json_response = (requests.get(url)).json()

    return json_response

In [2]:
def get_file_info(url, wojewodztwo):

    api_response = get_json_response(url)
    dict = api_response['data'][wojewodztwo]['attributes']

    for key in dict:
        print(key, ' : ', dict[key])

In [3]:
wojewodztwo = 14 # wielkopolskie

files_url = 'https://api.cepik.gov.pl/pliki'

get_file_info(files_url, wojewodztwo)

url-do-pliku  :  https://api.cepik.gov.pl/www/files/pojazdy_30_2022-04-17.zip
url-do-metadanych-pliku  :  https://api.cepik.gov.pl/www/meta/pojazdy_metadata.json
opis-zawartosci  :  Pojazdy z województwa wielkopolskiego
opis-formatu-pliku  :  CSV
typ-zasobu-bedacego-zawartoscia  :  pojazdy
data-utworzenia-pliku  :  2022-04-17

# Reading the data

In [3]:
import pandas as pd

# data = pd.read_csv(r'C:\Users\User\PycharmProjects\CEPiK_data\pojazdy_02_2022-04-17.csv')
data = pd.read_csv(r'C:\Users\szturminskid\Desktop\pojazdy_30_2022-04-17.csv')
data.head()

C:\Users\szturminskid\AppData\Local\Temp\ipykernel_13780\713653267.py:4: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\szturminskid\Desktop\pojazdy_30_2022-04-17.csv')

,pojazd_id,marka,kategoria,typ,model,wariant,wersja,rodzaj,podrodzaj,przeznaczenie,...,siedziba_wlasciciela_woj,siedziba_wlasciciela_pow,siedziba_wlasciciela_gmina,data_pierwszej_rej_w_kraju,createtimestamp,modifytimestamp,siedziba_wlasciciela_woj_teryt,akt_miejsce_rej_wojew_teryt,emisja_co2,emisja_co2_pal_alternatywne1
0,74579889452056,ACCESS,NaN,---,SP250,---,---,SAMOCHODOWY INNY,CZTEROKOŁOWIEC LEKKI,---,...,NaN,NaN,NaN,2017-07-28,2019-03-15,2019-03-15,NaN,30,NaN,NaN
1,56602518754772,NaN,NaN,NaN,POLSKI FIAT 126P 650,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,...,WIELKOPOLSKIE,KROTOSZYŃSKI,KROTOSZYN,1979-05-17,2019-03-15,2019-03-15,30.0,30,NaN,NaN
2,20923379525610,BMW,13.0,NaN,318,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,...,WIELKOPOLSKIE,PILSKI,WYRZYSK,2005-01-14,2019-03-15,2019-03-15,30.0,30,NaN,NaN
3,66334802582492,SAM,NaN,NaN,-,NaN,NaN,PRZYCZEPA LEKKA,CIĘŻAROWA,---,...,WIELKOPOLSKIE,ŚREDZKI,ŚRODA WIELKOPOLSKA,1993-07-22,2019-03-15,2019-03-15,30.0,30,NaN,NaN
4,944912486021,NaN,NaN,NaN,POLSKI FIAT 126P 650,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,...,WIELKOPOLSKIE,POZNAŃ,POZNAŃ,1992-01-02,2019-03-15,2019-03-15,30.0,30,NaN,NaN

In [6]:
data.columns

Index(['pojazd_id', 'marka', 'kategoria', 'typ', 'model', 'wariant', 'wersja',
       'rodzaj', 'podrodzaj', 'przeznaczenie', 'pochodzenie',
       'rodzaj_tab_znamionowej', 'rok_produkcji', 'sposob_produkcji',
       'data_pierwszej_rej', 'data_rejestracji_ost',
       'data_pierwszej_rej_za_granica', 'pojemnosc_silnika', 'moc_do_masy',
       'moc_silnika', 'moc_silnika_hybrydowego', 'masa_wlasna', 'masa_pgj',
       'dopuszczalna_masa_calkowita', 'maksymalna_masa_calkowita',
       'dopuszczalna_ladownosc_calk', 'maksymalna_ladownosc_calk',
       'dopuszczalna_masa_ciag_zesp', 'liczba_osi',
       'naj_dopuszczalny_nacisk_osi', 'naj_maksymalny_nacisk_osi',
       'max_masa_przyczepy_z_hamulcem', 'max_masa_przyczepy_bez_ham',
       'liczba_miejsc_ogolem', 'liczba_miejsc_siedzacych',
       'liczba_miejsc_stojacych', 'rodzaj_paliwa',
       'rodzaj_paliwa_alternatywnego', 'rodzaj_paliwa_alternatywnego2',
       'sr_zuzycie_pal', 'rodzaj_zawieszenia', 'radar', 'hak',
       'kierownica_polozenie', 'kierownica_z_prawej', 'katalizator',
       'producent_podstawowy', 'kod_ident', 'rozstaw_osi_kierowanej',
       'rozstaw_kol_max', 'rozstaw_kol_sred', 'rozstaw_kol_min',
       'emisja_co2_redukcja', 'wersja_rpp', 'kod_rpp', 'data_wyrejestrowania',
       'przyczyna_wyrejestrowania', 'data_wprowadzenia_danych',
       'akt_miejsce_rej_wojwe', 'akt_miejsce_rej_powiat',
       'akt_miejsce_rej_gmina', 'siedziba_wlasciciela_woj',
       'siedziba_wlasciciela_pow', 'siedziba_wlasciciela_gmina',
       'data_pierwszej_rej_w_kraju', 'createtimestamp', 'modifytimestamp',
       'siedziba_wlasciciela_woj_teryt', 'akt_miejsce_rej_wojew_teryt',
       'emisja_co2', 'emisja_co2_pal_alternatywne1'],
      dtype='object')

In [21]:
data['sr_zuzycie_pal'].describe()

count    196931.000000
mean          5.812867
std           2.814107
min           0.000000
25%           4.900000
50%           5.600000
75%           6.400000
max         424.800000
Name: sr_zuzycie_pal, dtype: float64

In [10]:
data.shape

(2254852, 71)

In [19]:
data['emisja_co2'].describe()

count    228811.000000
mean        138.835879
std          50.833160
min           0.000000
25%         119.000000
50%         137.000000
75%         156.000000
max       14137.000000
Name: emisja_co2, dtype: float64

In [22]:
data['emisja_co2_pal_alternatywne1'].describe()

count    354.000000
mean     145.901130
std       15.763257
min      114.000000
25%      132.000000
50%      150.000000
75%      163.000000
max      163.000000
Name: emisja_co2_pal_alternatywne1, dtype: float64

In [23]:
data.describe()

,pojazd_id,kategoria,pojemnosc_silnika,moc_do_masy,moc_silnika,moc_silnika_hybrydowego,masa_wlasna,masa_pgj,dopuszczalna_masa_calkowita,maksymalna_masa_calkowita,...,rozstaw_kol_max,rozstaw_kol_sred,rozstaw_kol_min,emisja_co2_redukcja,wersja_rpp,kod_rpp,siedziba_wlasciciela_woj_teryt,akt_miejsce_rej_wojew_teryt,emisja_co2,emisja_co2_pal_alternatywne1
count,2.254852e+06,6.693670e+05,2.102979e+06,238202.000000,1.738891e+06,2645.000000,2.254852e+06,915.000000,2.220812e+06,1.494666e+06,...,1.691720e+05,1.688520e+05,1.692830e+05,26.000000,1.318918e+06,1.318918e+06,1.663871e+06,2254852.0,228811.000000,354.000000
mean,4.171805e+14,9.008515e+12,1.787037e+03,0.054967,6.594840e+01,54.459486,1.255508e+03,2596.677596,2.485599e+03,2.556046e+03,...,1.311226e+03,1.679712e+03,1.303388e+03,12.423077,7.345808e+00,8.829512e+04,2.347350e+00,2.0,138.835879,145.901130
std,1.435587e+15,3.000068e+14,1.677351e+03,2.319208,5.822887e+01,32.067303,1.826548e+03,3332.014797,4.562420e+03,4.531931e+03,...,5.700606e+03,3.550240e+04,5.316251e+03,34.415314,3.239937e+00,2.188924e+05,2.631810e+00,0.0,50.833160,15.763257
min,6.146763e+07,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.800000,0.000000e+00,26.000000,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,2.0,0.000000,114.000000
25%,2.724473e+13,1.300000e+01,1.196000e+03,0.000000,4.000000e+01,45.000000,6.000000e+02,1360.000000,1.290000e+03,1.440000e+03,...,1.457000e+03,1.438000e+03,1.435000e+03,5.000000,9.000000e+00,3.000000e+00,2.000000e+00,2.0,119.000000,132.000000
50%,5.440014e+13,1.300000e+01,1.591000e+03,0.000000,6.600000e+01,53.000000,1.080000e+03,1696.000000,1.610000e+03,1.725000e+03,...,1.530000e+03,1.520000e+03,1.512000e+03,6.000000,9.000000e+00,3.000000e+00,2.000000e+00,2.0,137.000000,150.000000
75%,8.160095e+13,1.111111e+07,1.968000e+03,0.029300,8.500000e+01,69.160000,1.415000e+03,3152.500000,2.025000e+03,2.055000e+03,...,1.567000e+03,1.560000e+03,1.560000e+03,6.000000,9.000000e+00,9.000000e+00,2.000000e+00,2.0,156.000000,163.000000
max,9.007138e+15,1.000000e+16,9.999900e+04,920.000000,1.290200e+04,285.000000,9.999990e+05,42000.000000,9.209200e+05,4.600750e+05,...,1.685170e+06,7.451545e+06,1.540154e+06,181.000000,9.000000e+00,1.602000e+06,3.200000e+01,2.0,14137.000000,163.000000

In [6]:
data = data.set_index(data['pojazd_id'], drop=True)

In [9]:
data = data.drop('pojazd_id', axis=1)

In [10]:
data.head()

,marka,kategoria,typ,model,wariant,wersja,rodzaj,podrodzaj,przeznaczenie,pochodzenie,...,siedziba_wlasciciela_woj,siedziba_wlasciciela_pow,siedziba_wlasciciela_gmina,data_pierwszej_rej_w_kraju,createtimestamp,modifytimestamp,siedziba_wlasciciela_woj_teryt,akt_miejsce_rej_wojew_teryt,emisja_co2,emisja_co2_pal_alternatywne1
pojazd_id,,,,,,,,,,,,,,,,,,,,,
74579889452056,ACCESS,NaN,---,SP250,---,---,SAMOCHODOWY INNY,CZTEROKOŁOWIEC LEKKI,---,UŻYW. IMPORT INDYW,...,NaN,NaN,NaN,2017-07-28,2019-03-15,2019-03-15,NaN,30,NaN,NaN
56602518754772,NaN,NaN,NaN,POLSKI FIAT 126P 650,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,NOWY ZAKUPIONY W KRAJU,...,WIELKOPOLSKIE,KROTOSZYŃSKI,KROTOSZYN,1979-05-17,2019-03-15,2019-03-15,30.0,30,NaN,NaN
20923379525610,BMW,13.0,NaN,318,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,UŻYW. IMPORT INDYW,...,WIELKOPOLSKIE,PILSKI,WYRZYSK,2005-01-14,2019-03-15,2019-03-15,30.0,30,NaN,NaN
66334802582492,SAM,NaN,NaN,-,NaN,NaN,PRZYCZEPA LEKKA,CIĘŻAROWA,---,NOWY ZAKUPIONY W KRAJU,...,WIELKOPOLSKIE,ŚREDZKI,ŚRODA WIELKOPOLSKA,1993-07-22,2019-03-15,2019-03-15,30.0,30,NaN,NaN
944912486021,NaN,NaN,NaN,POLSKI FIAT 126P 650,NaN,NaN,SAMOCHÓD OSOBOWY,---,---,UŻYW. ZAKUPIONY W KRAJU,...,WIELKOPOLSKIE,POZNAŃ,POZNAŃ,1992-01-02,2019-03-15,2019-03-15,30.0,30,NaN,NaN

In [12]:
data['emisja_co2'].describe()

count    307993.000000
mean        129.063293
std         368.897074
min           0.000000
25%         114.000000
50%         133.000000
75%         153.000000
max      202817.000000
Name: emisja_co2, dtype: float64

In [13]:
#df= df.dropna(subset=['Attrition'])

data = data.dropna(subset='emisja_co2')

In [14]:
data.shape

(307993, 70)